# Generated by Django 4.1.1 on 2022-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500)),
                ('Role', models.CharField(max_length=500)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('ContactNumber', models.CharField(max_length=500)),
            ],
        ),
    ]
