# Generated by Django 4.1.1 on 2022-09-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_user_contactnumber_alter_user_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserId',
            new_name='idUser',
        ),
    ]
