# Generated by Django 4.1.1 on 2022-09-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_rename_userid_user_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idUser',
            new_name='UserId',
        ),
    ]
