# Generated by Django 4.1.1 on 2022-10-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountCreatTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Account Creation Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contactNumber',
            field=models.CharField(blank=True, max_length=500, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(blank=True, max_length=8, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last Login Time'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(blank=True, max_length=8, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=16, verbose_name='Username'),
        ),
    ]
