# Generated by Django 4.1.1 on 2022-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_user_accountcreattime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='accountCreatTime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
