# Generated by Django 4.1.1 on 2022-11-06 22:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_user_lastlogintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
