# Generated by Django 4.1.1 on 2022-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('desciption', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('desciption', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('nameBrand', models.CharField(default='default', max_length=32)),
                ('quantity', models.IntegerField(default=1)),
                ('nameLocation', models.CharField(default='default', max_length=16)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('desciption', models.CharField(blank=True, max_length=64, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('dateBestBefore', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('conditionStorage', models.CharField(choices=[('Frozen(below -4 degrees)', 'Frozen(below -4 degrees)'), ('Normal', 'Normal'), ('Refrigeration', 'Refrigeration')], default='default', max_length=32)),
                ('category', models.CharField(choices=[('Appliances', 'Appliances'), ('Apps & Games', 'Apps & Games'), ('Arts, Handicrafts & Sewing', 'Arts, Handicrafts & Sewing'), ('Automotive Parts & Accessories', 'Automotive Parts & Accessories'), ('Baby', 'Baby'), ('Baggage & Travel Equipment', 'Baggage & Travel Equipment'), ('Beauty', 'Beauty'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('CDs & Vinyl', 'CDs & Vinyl'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('Centurion Garden & Outdoor', 'Centurion Garden & Outdoor'), ('Clothing, Shoes and Jewelry', 'Clothing, Shoes and Jewelry'), ('Collectibles & Fine Art', 'Collectibles & Fine Art'), ('Computers & Electronics', 'Computers & Electronics'), ('Film Supplies', 'Film Supplies'), ('Food', 'Food'), ('Handcrafts', 'Handcrafts'), ('Health & Baby Care', 'Health & Baby Care'), ('Household & Kitchen Appliances', 'Household & Kitchen Appliances'), ('Industrial & Scientific Supplies', 'Industrial & Scientific Supplies'), ('Musical Instrument', 'Musical Instrument'), ('Others', 'Others'), ('Pet Supplies', 'Pet Supplies'), ('Sports & Outdoor', 'Sports & Outdoor'), ('Tools & Home Decoration', 'Tools & Home Decoration'), ('Video Games', 'Video Games'), ('Toys & Games', 'Toys & Games')], default='default', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('nameLocation', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('nameRegion', models.CharField(max_length=16)),
                ('idItem', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('nameRegion', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
                ('usage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
