# Generated by Django 4.1 on 2022-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='inventory',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=19),
        ),
    ]
