# Generated by Django 4.1.1 on 2022-09-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_brand_inventory_category_inventory_item_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('idItem', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('nameBrand', models.CharField(default='default', max_length=32)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nameLocation', models.CharField(default='default', max_length=16)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
